### PR TITLE
catch Stan log_prob exceptions inside moment matching

### LINKED ISSUE #261: Stan log_prob exceptions cause moment_matching to fail
Reported in Stan discourse with reproducible example
https://discourse.mc-stan.org/t/add-criterion-with-moment-match-true-failing-even-when-save-pars-all-true-was-set-during-model-fit/30956/13

The moment matching transformed unconstrained parameter values can under- or overflow when constrained or some further quantity in the Stan program can under- or overflow. In this example one of the variables inside the model is 0, while should be positive. This causes an exception, which causes an error in R and moment_matching quits:
```
Error : Exception: beta_lpdf: Second shape parameter is 0, but must be positive finite! (in 'string', line 226, column 6 to column 111)
```

`brms` catches this error, but makes only one guess for the reason
```
Error: Moment matching failed. Perhaps you did not set 'save_pars = save_pars(all = TRUE)' when fitting your model? If you are running moment matching on another machine than the one used to fit the model, you may need to set recompile = TRUE.
```

### PR DESCRIPTION
**Pull request by avehtari**
Fixes #261

When doing moment matching steps, catch the errors when evaluating log_prob, and break out without an error. This will allow getting moment matching results for all the non-failing observations and may get some moment matching also for the failing ones.

### CODE REVIEW

File: R/loo_moment_matching.R [hunk 1]
```diff
@@ -336,15 +348,21 @@ loo_moment_match_i <- function(i,
...
                                           orig_log_prob = orig_log_prob,
                                           log_prob_upars = log_prob_upars,
                                           log_lik_i_upars = log_lik_i_upars,
                                           r_eff_i = r_eff_i,
                                           cores = 1,
                                           is_method = is_method,
                                           ...)
+                          )
 
+      if (is_try_error(quantities_i)) {
```
Comment (jgabry) [inline R/loo_moment_matching.R:361]:
```suggestion
      if (inherits(quantities_i, "try-error")) {
```

File: R/loo_moment_matching.R [hunk 2]
```diff
@@ -310,14 +316,20 @@ loo_moment_match_i <- function(i,
...
+    quantities_i <- try(update_quantities_i(x, trans$upars,  i = i,
                                         orig_log_prob = orig_log_prob,
                                         log_prob_upars = log_prob_upars,
                                         log_lik_i_upars = log_lik_i_upars,
                                         r_eff_i = r_eff_i,
                                         cores = 1,
                                         is_method = is_method,
                                         ...)
+                        )
+    if (is_try_error(quantities_i)) {
```
Comment (jgabry) [inline R/loo_moment_matching.R:328]:
```suggestion
    if (inherits(quantities_i, "try-error")) {
```

File: R/loo_moment_matching.R [hunk 3]
```diff
@@ -286,14 +286,20 @@ loo_moment_match_i <- function(i,
...
+    quantities_i <- tryCatch(update_quantities_i(x, trans$upars,  i = i,
                                         orig_log_prob = orig_log_prob,
                                         log_prob_upars = log_prob_upars,
                                         log_lik_i_upars = log_lik_i_upars,
                                         r_eff_i = r_eff_i,
                                         cores = 1,
                                         is_method = is_method,
                                         ...)
+                        )
+    if (is_try_error(quantities_i)) {
```
Comment (jgabry) [inline R/loo_moment_matching.R:298]: I don't think `is_try_error` is a base R function. Is this from a package? I think not finding this function is causing the unit test errors. If you use `try` then you can do

```suggestion
    if (inherits(quantities_i, "try-error")) {
```

File: R/loo_moment_matching.R [hunk 4]
```diff
@@ -286,14 +286,20 @@ loo_moment_match_i <- function(i,
     # 1. match means
     trans <- shift(x, uparsi, lwi)
     # gather updated quantities
-    quantities_i <- update_quantities_i(x, trans$upars,  i = i,
+    quantities_i <- tryCatch(update_quantities_i(x, trans$upars,  i = i,
```
Comment (jgabry) [inline R/loo_moment_matching.R:289]:
```suggestion
    quantities_i <- try(update_quantities_i(x, trans$upars,  i = i,
```

Here you were using `tryCatch` but in the other cases below you use `try`. I would just use `try` everywhere for consistency (it's also simpler to use than `tryCatch`).

**Review by jgabry — CHANGES_REQUESTED** [review]
This seems like a good idea. I made a few small suggestions in review comments.

File: R/loo_moment_matching.R (hunk 3 above)
Comment (avehtari) [reply R/loo_moment_matching.R:298]: Oops, `is_try_error` is from `brms` and I forgot to run tests in fresh R session

**Comment by avehtari** [comment]
Thanks for fixes! I need to remember to run tests in *fresh* R session. I was learning `try` and `TryCatch` and for a moment thought I might need the latter, and for some reason didn't see that it was still there

**Review by jgabry — APPROVED** [review]
