### PR TITLE
Fix bug in IS method error message + documentation typos

### LINKED ISSUE #325: Bug in error message for invalid IS method + several documentation typos
Hi! I was reading through the codebase and noticed a small bug and a few typos scattered across the source and docs.

### Bug: `implemented_is_methods` called without parentheses

In `R/importance_sampling.R` (line 117), `implemented_is_methods` is referenced without `()` inside the `paste0()` call:

```r
paste0(implemented_is_methods, collapse = "', '")
```

Since `implemented_is_methods` is a function (defined on line 121), this pastes the function object's string representation instead of the actual method names (`"psis"`, `"tis"`, `"sis"`). The check on line 113 correctly uses `implemented_is_methods()` with parentheses, but the error message construction doesn't.

### Typos in documentation (roxygen + .Rd files)

While reading through the code I also spotted a handful of typos:

| File | Typo | Fix |
|------|------|-----|
| `R/diagnostics.R` (line 14) | "dependend" | "dependent" |
| `R/diagnostics.R` (line 433) | "dependend k-ht" | "dependent k-hat" |
| `R/loo-glossary.R` (line 10) | "The pages provides definitions to" | "The page provides definitions of" |
| `R/split_moment_matching.R` (line 24) | "log-likeliood" | "log-likelihood" |
| `R/loo_subsample.R` (line 420) | "subampled" | "subsampled" |
| `R/loo_compare.psis_loo_ss_list.R` (line 34) | "comaprison" | "comparison" |
| `R/loo_model_weights.R` (line 10) | "matrices or , one for each" | "matrices, one for each" |
| `R/loo-package.R` (line 85) | "widely application" | "widely applicable" |

The corresponding `.Rd` man pages have the same typos (generated from roxygen).

Happy to submit a PR for these if that would be helpful!

### PR DESCRIPTION
**Pull request by ishaan-arora-1**
Hey! I was going through the codebase and spotted a small bug along with some typos. Figured I'd clean them up in one go.

## Bug fix

In `R/importance_sampling.R`, the function `assert_importance_sampling_method_is_implemented()` constructs an error message when an unsupported importance sampling method is passed. On line 117, `implemented_is_methods` is used without `()`:

```r
paste0(implemented_is_methods, collapse = "', '")
```

Since `implemented_is_methods` is a function, this ends up pasting the function object itself into the error message instead of the actual method names (`"psis"`, `"tis"`, `"sis"`). The condition check on line 113 correctly calls `implemented_is_methods()`, so this was just missed in the message string.

## Typos

While reading through the source I also noticed these scattered across the roxygen comments:

- **diagnostics.R**: "dependend" → "dependent", "k-ht" → "k-hat"
- **loo-glossary.R**: "The pages provides definitions to" → "The page provides definitions of"
- **split_moment_matching.R**: "log-likeliood" → "log-likelihood"
- **loo_subsample.R**: "subampled" → "subsampled"
- **loo_compare.psis_loo_ss_list.R**: "comaprison" → "comparison"
- **loo_model_weights.R**: "matrices or , one for each" → "matrices, one for each"
- **loo-package.R**: "widely application" → "widely applicable" (Watanabe 2010 reference)

I also updated the corresponding `.Rd` man pages to match.

Fixes #325

### CODE REVIEW

File: R/waic.R [hunk 1]
```diff
@@ -1,167 +1,167 @@
...
+    count <- sum(badp)
+    prop <- count / length(badp)
+    msg <- paste0("\n", count, " (", .fr(100 * prop, digits),
+                  "%) p_waic estimates greater than 0.4. ",
+                  "We recommend trying loo instead.")
+    if (warn) .warn(msg) else cat(msg, "\n")
+  }
+  invisible(NULL)
+}
+
```
Comment (jgabry) [inline R/waic.R]: @ishaan-arora-1 @VisruthSK Any idea why this entire file shows up in the diff when there's just a single typo fix?

Comment (VisruthSK) [reply R/waic.R]: Hm that is weird. Could be line endings? If @ishaan-arora-1 is on Windows and maybe sets something in Git maybe it overrides the .gitattributes?

**Comment by jgabry** [comment]
Great, thanks!
